name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CI_CFLAGS: -O2 -Wall -Wextra -Wshadow -Werror -pedantic
  CI_CSTD: -std=c11
  CI_CXXSTD: -std=c++17
  CI_DEPS_XCB: libxcb-xtest0-dev
  CI_DEPS_QT5: qtbase5-dev qttools5-dev-tools libqt5x11extras5-dev
  CI_DEPS_QT6: qt6-base-dev qt6-base-dev-tools qt6-l10n-tools

jobs:
  build-qt5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build-depends
      run: |
        sudo apt-get -y install ${CI_DEPS_XCB} ${CI_DEPS_QT5}
    - name: build
      run: |
        make -j4 QT_VERSION=5 \
            CFLAGS="${CI_CSTD} ${CI_CFLAGS}" \
            CXXFLAGS="${CI_CXXSTD} ${CI_CFLAGS}"
  build-qt6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build-depends
      run: |
        sudo apt-get -y install ${CI_DEPS_XCB} ${CI_DEPS_QT6}
    - name: build
      run: |
        PKG_CONFIG_PATH=$(pwd)/.github/pkgconfig make -j4 \
            CFLAGS="${CI_CSTD} ${CI_CFLAGS}" \
            CXXFLAGS="${CI_CXXSTD} ${CI_CFLAGS}"
